#Requires -RunAsAdministrator
<#
.SYNOPSIS
    CIS Windows Hardening Script
.DESCRIPTION
    Consolidated hardening script for 5 CIS rules.
    Generated by CIS Hardening Platform.

    WARNING: Review each rule before applying to production systems.
#>

param(
    [switch]$WhatIf
)

$ErrorActionPreference = 'Stop'
$Script:Results = @()

function Write-RuleResult {
    param([string]$RuleId, [string]$Title, [string]$Status, [string]$Details)
    $Script:Results += [PSCustomObject]@{
        RuleId = $RuleId; Title = $Title; Status = $Status; Details = $Details
    }
    $color = switch ($Status) {
        'PASS' { 'Green' }
        'FAIL' { 'Red' }
        'APPLIED' { 'Cyan' }
        default { 'Yellow' }
    }
    Write-Host "[${Status}] ${RuleId}: ${Title}" -ForegroundColor $color
    if ($Details) { Write-Host "       $Details" -ForegroundColor Gray }
}

# ── CIS 18.1.1.1 ──────────────────────────────────────
function Apply-CIS_18_1_1_1 {
    <#
    .SYNOPSIS
        Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'
    .NOTES
        Category:       Administrative Templates
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "18.1.1.1" -Title "Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        if (-not (Test-Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization')) { New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization' -Force -ErrorAction SilentlyContinue }; Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenCamera' -Value 1 -Type DWord -Force
        Write-RuleResult -RuleId "18.1.1.1" -Title "Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "18.1.1.1" -Title "Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 18.1.1.2 ──────────────────────────────────────
function Apply-CIS_18_1_1_2 {
    <#
    .SYNOPSIS
        Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'
    .NOTES
        Category:       Administrative Templates
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "18.1.1.2" -Title "Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        if (-not (Test-Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization')) { New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization' -Force -ErrorAction SilentlyContinue }; Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenSlideshow' -Value 1 -Type DWord -Force
        Write-RuleResult -RuleId "18.1.1.2" -Title "Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "18.1.1.2" -Title "Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 18.1.3 ──────────────────────────────────────
function Apply-CIS_18_1_3 {
    <#
    .SYNOPSIS
        Ensure 'Allow Online Tips' is set to 'Disabled'
    .NOTES
        Category:       Administrative Templates
        CIS Level:      2
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "18.1.3" -Title "Ensure 'Allow Online Tips' is set to 'Disabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        if (-not (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer')) { New-Item -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Force -ErrorAction SilentlyContinue }; Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'AllowOnlineTips' -Value 0 -Type DWord -Force
        Write-RuleResult -RuleId "18.1.3" -Title "Ensure 'Allow Online Tips' is set to 'Disabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "18.1.3" -Title "Ensure 'Allow Online Tips' is set to 'Disabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 18.1.2.2 ──────────────────────────────────────
function Apply-CIS_18_1_2_2 {
    <#
    .SYNOPSIS
        Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'
    .NOTES
        Category:       Administrative Templates
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "18.1.2.2" -Title "Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        if (-not (Test-Path 'HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization')) { New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization' -Force -ErrorAction SilentlyContinue }; Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization' -Name 'AllowInputPersonalization' -Value 0 -Type DWord -Force
        Write-RuleResult -RuleId "18.1.2.2" -Title "Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "18.1.2.2" -Title "Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 18.4.1 ──────────────────────────────────────
function Apply-CIS_18_4_1 {
    <#
    .SYNOPSIS
        Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver (recommended)'
    .NOTES
        Category:       Administrative Templates
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "18.4.1" -Title "Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver (recommended)'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        if (-not (Test-Path 'HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10')) { New-Item -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10' -Force -ErrorAction SilentlyContinue }; Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10' -Name 'Start' -Value 4 -Type DWord -Force
        Write-RuleResult -RuleId "18.4.1" -Title "Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver (recommended)'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "18.4.1" -Title "Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver (recommended)'" -Status "FAIL" -Details $_.Exception.Message
    }
}


# ══════════════════════════════════════════════════════════════
# Main Execution
# ══════════════════════════════════════════════════════════════

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  CIS Windows Hardening – 5 Rules" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

Apply-CIS_18_1_1_1
Apply-CIS_18_1_1_2
Apply-CIS_18_1_3
Apply-CIS_18_1_2_2
Apply-CIS_18_4_1

# Summary
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
$applied = ($Script:Results | Where-Object Status -eq "APPLIED").Count
$failed  = ($Script:Results | Where-Object Status -eq "FAIL").Count
$skipped = ($Script:Results | Where-Object Status -eq "SKIPPED").Count
Write-Host "Applied: $applied  |  Failed: $failed  |  Skipped: $skipped" -ForegroundColor White
Write-Host "================================================================" -ForegroundColor Cyan

