#Requires -RunAsAdministrator
<#
.SYNOPSIS
    CIS Windows Hardening Script
.DESCRIPTION
    Consolidated hardening script for 10 CIS rules.
    Generated by CIS Hardening Platform.

    WARNING: Review each rule before applying to production systems.
#>

param(
    [switch]$WhatIf
)

$ErrorActionPreference = 'Stop'
$Script:Results = @()

function Write-RuleResult {
    param([string]$RuleId, [string]$Title, [string]$Status, [string]$Details)
    $Script:Results += [PSCustomObject]@{
        RuleId = $RuleId; Title = $Title; Status = $Status; Details = $Details
    }
    $color = switch ($Status) {
        'PASS' { 'Green' }
        'FAIL' { 'Red' }
        'APPLIED' { 'Cyan' }
        default { 'Yellow' }
    }
    Write-Host "[${Status}] ${RuleId}: ${Title}" -ForegroundColor $color
    if ($Details) { Write-Host "       $Details" -ForegroundColor Gray }
}

# ── CIS 1.1.1 ──────────────────────────────────────
function Apply-CIS_1_1_1 {
    <#
    .SYNOPSIS
        Ensure 'Enforce password history' is set to '24 or more password(s)'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.1" -Title "Ensure 'Enforce password history' is set to '24 or more password(s)'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        
        # Export current security policy
        secedit /export /cfg $seceditExport /quiet
        
        # Read and modify
        $content = Get-Content $seceditExport
        $content = $content -replace 'PasswordHistorySize\s*=\s*\d+', 'PasswordHistorySize = 24'
        
        # If setting doesn't exist, add it
        if ($content -notmatch 'PasswordHistorySize') {
            $content = $content -replace '(\[System Access\])', "`$1`nPasswordHistorySize = 24"
        }
        
        $content | Set-Content $seceditImport -Force
        
        # Import modified policy
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        
        # Cleanup
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.1.1" -Title "Ensure 'Enforce password history' is set to '24 or more password(s)'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.1" -Title "Ensure 'Enforce password history' is set to '24 or more password(s)'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.1.2 ──────────────────────────────────────
function Apply-CIS_1_1_2 {
    <#
    .SYNOPSIS
        Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.2" -Title "Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'MaximumPasswordAge\s*=\s*\d+', 'MaximumPasswordAge = 365'
        if ($content -notmatch 'MaximumPasswordAge') {
            $content = $content -replace '(\[System Access\])', "`$1`nMaximumPasswordAge = 365"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.1.2" -Title "Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.2" -Title "Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.1.3 ──────────────────────────────────────
function Apply-CIS_1_1_3 {
    <#
    .SYNOPSIS
        Ensure 'Minimum password age' is set to '1 or more day(s)'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.3" -Title "Ensure 'Minimum password age' is set to '1 or more day(s)'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'MinimumPasswordAge\s*=\s*\d+', 'MinimumPasswordAge = 1'
        if ($content -notmatch 'MinimumPasswordAge') {
            $content = $content -replace '(\[System Access\])', "`$1`nMinimumPasswordAge = 1"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.1.3" -Title "Ensure 'Minimum password age' is set to '1 or more day(s)'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.3" -Title "Ensure 'Minimum password age' is set to '1 or more day(s)'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.1.4 ──────────────────────────────────────
function Apply-CIS_1_1_4 {
    <#
    .SYNOPSIS
        Ensure 'Minimum password length' is set to '14 or more character(s)'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.4" -Title "Ensure 'Minimum password length' is set to '14 or more character(s)'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'MinimumPasswordLength\s*=\s*\d+', 'MinimumPasswordLength = 14'
        if ($content -notmatch 'MinimumPasswordLength') {
            $content = $content -replace '(\[System Access\])', "`$1`nMinimumPasswordLength = 14"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.1.4" -Title "Ensure 'Minimum password length' is set to '14 or more character(s)'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.4" -Title "Ensure 'Minimum password length' is set to '14 or more character(s)'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.1.5 ──────────────────────────────────────
function Apply-CIS_1_1_5 {
    <#
    .SYNOPSIS
        Ensure 'Password must meet complexity requirements' is set to 'Enabled'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.5" -Title "Ensure 'Password must meet complexity requirements' is set to 'Enabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'PasswordComplexity\s*=\s*\d+', 'PasswordComplexity = 1'
        if ($content -notmatch 'PasswordComplexity') {
            $content = $content -replace '(\[System Access\])', "`$1`nPasswordComplexity = 1"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.1.5" -Title "Ensure 'Password must meet complexity requirements' is set to 'Enabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.5" -Title "Ensure 'Password must meet complexity requirements' is set to 'Enabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.1.6 ──────────────────────────────────────
function Apply-CIS_1_1_6 {
    <#
    .SYNOPSIS
        Ensure 'Relax minimum password length limits' is set to 'Enabled'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.6" -Title "Ensure 'Relax minimum password length limits' is set to 'Enabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        if (-not (Test-Path 'HKLM:\System\CurrentControlSet\Control\SAM')) {
            New-Item -Path 'HKLM:\System\CurrentControlSet\Control\SAM' -Force | Out-Null
        }
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\SAM' -Name 'RelaxMinimumPasswordLengthLimits' -Value 1 -Type DWord -Force
        Write-RuleResult -RuleId "1.1.6" -Title "Ensure 'Relax minimum password length limits' is set to 'Enabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.6" -Title "Ensure 'Relax minimum password length limits' is set to 'Enabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.1.7 ──────────────────────────────────────
function Apply-CIS_1_1_7 {
    <#
    .SYNOPSIS
        Ensure 'Store passwords using reversible encryption' is set to 'Disabled'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.1.7" -Title "Ensure 'Store passwords using reversible encryption' is set to 'Disabled'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'ClearTextPassword\s*=\s*\d+', 'ClearTextPassword = 0'
        if ($content -notmatch 'ClearTextPassword') {
            $content = $content -replace '(\[System Access\])', "`$1`nClearTextPassword = 0"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.1.7" -Title "Ensure 'Store passwords using reversible encryption' is set to 'Disabled'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.1.7" -Title "Ensure 'Store passwords using reversible encryption' is set to 'Disabled'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.2.1 ──────────────────────────────────────
function Apply-CIS_1_2_1 {
    <#
    .SYNOPSIS
        Ensure 'Account lockout duration' is set to '15 or more minute(s)'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.2.1" -Title "Ensure 'Account lockout duration' is set to '15 or more minute(s)'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'LockoutDuration\s*=\s*\d+', 'LockoutDuration = 15'
        if ($content -notmatch 'LockoutDuration') {
            $content = $content -replace '(\[System Access\])', "`$1`nLockoutDuration = 15"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.2.1" -Title "Ensure 'Account lockout duration' is set to '15 or more minute(s)'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.2.1" -Title "Ensure 'Account lockout duration' is set to '15 or more minute(s)'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.2.2 ──────────────────────────────────────
function Apply-CIS_1_2_2 {
    <#
    .SYNOPSIS
        Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.2.2" -Title "Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'LockoutBadCount\s*=\s*\d+', 'LockoutBadCount = 5'
        if ($content -notmatch 'LockoutBadCount') {
            $content = $content -replace '(\[System Access\])', "`$1`nLockoutBadCount = 5"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.2.2" -Title "Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.2.2" -Title "Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'" -Status "FAIL" -Details $_.Exception.Message
    }
}

# ── CIS 1.2.4 ──────────────────────────────────────
function Apply-CIS_1_2_4 {
    <#
    .SYNOPSIS
        Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'
    .NOTES
        Category:       Account Policies
        CIS Level:      1
        Requires Admin: True
        Requires Reboot:False
    #>
    try {
        if ($WhatIf) {
            Write-RuleResult -RuleId "1.2.4" -Title "Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'" -Status "SKIPPED" -Details "WhatIf mode"
            return
        }
        $seceditExport = "$env:TEMP\secpol_export.cfg"
        $seceditImport = "$env:TEMP\secpol_import.cfg"
        secedit /export /cfg $seceditExport /quiet
        $content = Get-Content $seceditExport
        $content = $content -replace 'ResetLockoutCount\s*=\s*\d+', 'ResetLockoutCount = 15'
        if ($content -notmatch 'ResetLockoutCount') {
            $content = $content -replace '(\[System Access\])', "`$1`nResetLockoutCount = 15"
        }
        $content | Set-Content $seceditImport -Force
        secedit /configure /db secedit.sdb /cfg $seceditImport /quiet
        Remove-Item $seceditExport, $seceditImport -Force -ErrorAction SilentlyContinue
        Write-RuleResult -RuleId "1.2.4" -Title "Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'" -Status "APPLIED" -Details "Successfully applied"
    }
    catch {
        Write-RuleResult -RuleId "1.2.4" -Title "Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'" -Status "FAIL" -Details $_.Exception.Message
    }
}


# ══════════════════════════════════════════════════════════════
# Main Execution
# ══════════════════════════════════════════════════════════════

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  CIS Windows Hardening – 10 Rules" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

Apply-CIS_1_1_1
Apply-CIS_1_1_2
Apply-CIS_1_1_3
Apply-CIS_1_1_4
Apply-CIS_1_1_5
Apply-CIS_1_1_6
Apply-CIS_1_1_7
Apply-CIS_1_2_1
Apply-CIS_1_2_2
Apply-CIS_1_2_4

# Summary
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
$applied = ($Script:Results | Where-Object Status -eq "APPLIED").Count
$failed  = ($Script:Results | Where-Object Status -eq "FAIL").Count
$skipped = ($Script:Results | Where-Object Status -eq "SKIPPED").Count
Write-Host "Applied: $applied  |  Failed: $failed  |  Skipped: $skipped" -ForegroundColor White
Write-Host "================================================================" -ForegroundColor Cyan

